name: software-carpentries-scikit-hep-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.9
  - awkward
  - hist
  - lz4
  - matplotlib
  - mplhep
  - numba
  - numpy
  - pandas
  - python-xxhash
  - uproot
  - xrootd
  - zfit
  - zstandard
  - pip
  - pip:
      - vector
      - particle
      - fastjet
      - scikit-hep-testdata
