name: software-carpentries-scikit-hep-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.9
  - hist==2.5.2
  - lz4==3.1.10
  - matplotlib==3.5.1
  - mplhep==0.3.15
  - numba==0.54.1
  - numpy==1.19.5
  - pandas==1.3.5
  - python-xxhash==2.0.2
  - xrootd==5.3.4
  - zstandard==0.16.0
  - pip==21.3.1
  - pip:
      - awkward==1.7.0
      - fastjet==0.0.1.1
      - particle==0.16.2
      - scikit-hep-testdata==0.4.11
      - uproot==4.1.9
      - vector==0.8.4
      - zfit==0.8.2
